version: '3'

services:
  master:
    image: redis:5.0.5
    ports:
      - 6379:6379
    networks:
      - redis_network

  slave_01:
    image: redis:5.0.5
    command: redis-server --slaveof master 6379
    ports:
      - 6380:6379
    networks:
      - redis_network
  
  slave_02:
    image: redis:5.0.5
    command: redis-server --slaveof master 6379
    ports:
      - 6381:6379
    networks:
      - redis_network

  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    networks:
      - redis_network

  proxy:
    build: ./haproxy
    depends_on:
      - master
      - slave_01
      - slave_02
    networks:
      - redis_network
    ports:
      - 9000:9000
      - 8080:80

networks:
  redis_network:
    driver: bridge
