version: '3'

services:
  master:
    build: ./master
    ports:
      - 6379:6379
    networks:
      - redis_network
    restart: unless-stopped

  slave_01:
    build: ./slave
    ports:
      - 6380:6379
    networks:
      - redis_network
    restart: unless-stopped
  
  slave_02:
    build: ./slave
    ports:
      - 6381:6379
    networks:
      - redis_network
    restart: unless-stopped

  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    networks:
      - redis_network
    restart: unless-stopped

  proxy:
    build: ./haproxy
    depends_on:
      - master
      - slave_01
      - slave_02
    networks:
      - redis_network
    ports:
      - 9000:9000
      - 8080:80
    restart: unless-stopped

networks:
  redis_network:
    driver: bridge
